services:
  trilium:
    image: triliumnext/notes:latest
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TZ=Asia/Jerusalem
    ports:
      - '8080'
    networks:
      - coolify
    volumes:
      - /data:/home/node/trilium-data
      - /usr/share/zoneinfo/Asia/Jerusalem:/etc/timezone:ro
      - /usr/share/zoneinfo/Asia/Jerusalem:/etc/localtime:ro

networks:
  coolify:
    external: true
