services:
  trilium:
    image: triliumnext/notes:latest   
    container_name: trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TZ=Asia/Jerusalem
    ports:
      - '8180:8080'    
    networks:
      - coolify
    volumes:
      - /data/trilium/storage:/home/node/trilium-data    
      - /usr/share/zoneinfo/Asia/Jerusalem:/etc/timezone:ro
      - /usr/share/zoneinfo/Asia/Jerusalem:/etc/localtime:ro
    labels:
      - coolify.managed=true

volumes:
  trilium-data:    

networks:
  coolify:
    external: true
